# Generated by Django 2.2 on 2023-04-07 23:06

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.TextField(unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.TextField()),
                ("verified", models.BooleanField(default=False)),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("short_bio", models.TextField(blank=True, default="")),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True,
                        default="profiles/sample.jpg",
                        null=True,
                        upload_to=api.models.upload_to,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserTest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.TextField()),
                ("email", models.EmailField(max_length=254)),
                ("password", models.TextField()),
                ("verified", models.BooleanField(default=False)),
                ("short_bio", models.TextField(blank=True, default="")),
            ],
        ),
        migrations.CreateModel(
            name="RecoverRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.TextField()),
                ("used", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.User"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OTP_Request",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otp", models.TextField()),
                ("verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("tries", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.User"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "followed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followed",
                        to="api.User",
                    ),
                ),
                (
                    "follows",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follows",
                        to="api.User",
                    ),
                ),
            ],
        ),
    ]
