# Generated by Django 2.2 on 2023-04-07 14:44

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileImageModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default=None,
                        null=True,
                        upload_to="",
                        validators=[api.models.ProfileImageModel.validate_image],
                    ),
                ),
                ("title", models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="picture",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.ProfileImageModel",
            ),
        ),
    ]
