# Generated by Django 4.1.6 on 2023-03-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_auto_20230227_0334"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
