# Generated by Django 2.2 on 2023-03-06 06:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_auto_20230227_0334"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.TextField(unique=True),
        ),
        migrations.CreateModel(
            name="OTP_Request",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otp", models.TextField()),
                ("verified", models.BooleanField(default=False)),
                (
                    "created_at",
                    models.DateField(default=datetime.date.today, verbose_name="Date"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.User"
                    ),
                ),
            ],
        ),
    ]
