# Generated by Django 3.2 on 2023-03-30 16:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_auto_20230329_2005"),
        ("api", "0013_auto_20230330_1603"),
    ]

    operations = []
