# Generated by Django 2.2 on 2023-03-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_auto_20230330_1628"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="followers",
        ),
        migrations.RemoveField(
            model_name="usertest",
            name="followers",
        ),
        migrations.AddField(
            model_name="user",
            name="follows",
            field=models.TextField(blank=True, null=True),
        ),
    ]
