# Generated by Django 2.2 on 2023-03-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_user_followed_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="followed_by",
            field=models.ManyToManyField(
                blank=True, related_name="followed_by_users", to="api.User"
            ),
        ),
    ]
