# Generated by Django 2.2 on 2023-03-31 19:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0021_merge_20230331_1734"),
        ("api", "0015_user_profile_pic"),
    ]

    operations = []
