# Generated by Django 2.2 on 2023-04-02 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_merge_20230331_1919'),
        ('api', '0022_auto_20230331_1841'),
    ]

    operations = [
    ]
