# Generated by Django 2.2 on 2023-03-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_auto_20230306_0643"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
