# Generated by Django 2.2 on 2023-03-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_user_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp_request",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
