# Generated by Django 4.1.6 on 2023-03-19 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Crawl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(max_length=500, null=True)),
                ("author", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CrawlPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crawl",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crawls.crawl",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CrawlTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "point",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crawls.crawl",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "crawls",
                    models.ManyToManyField(
                        blank=True, through="crawls.CrawlTag", to="crawls.crawl"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Point",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(max_length=500, null=True)),
                ("google_place_id", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("longitude", models.FloatField(null=True)),
                ("latitude", models.FloatField(null=True)),
                ("address", models.TextField(max_length=200, null=True)),
                (
                    "crawls",
                    models.ManyToManyField(
                        blank=True, through="crawls.CrawlPoint", to="crawls.crawl"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="crawltag",
            name="tag",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="crawls.tag"
            ),
        ),
        migrations.AddField(
            model_name="crawlpoint",
            name="point",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="crawls.point",
            ),
        ),
        migrations.AddField(
            model_name="crawl",
            name="points",
            field=models.ManyToManyField(
                blank=True, through="crawls.CrawlPoint", to="crawls.point"
            ),
        ),
        migrations.AddField(
            model_name="crawl",
            name="tags",
            field=models.ManyToManyField(
                blank=True, through="crawls.CrawlTag", to="crawls.tag"
            ),
        ),
    ]
