# Generated by Django 4.1.6 on 2023-03-19 19:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crawls", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="crawltag",
            old_name="point",
            new_name="crawl",
        ),
    ]
