# Generated by Django 2.2 on 2023-04-07 14:35

import crawls.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("crawls", "0007_auto_20230405_1638"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default=None,
                        null=True,
                        upload_to="",
                        validators=[crawls.models.ImageModel.validate_image],
                    ),
                ),
                ("title", models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name="crawl",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="crawl",
            name="picture",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="crawls.ImageModel",
            ),
        ),
    ]
