# Generated by Django 3.2 on 2023-04-10 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_user_profile_pic"),
        ("crawls", "0009_crawl_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crawl",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author",
                to="api.user",
            ),
        ),
    ]
