# Generated by Django 2.2 on 2023-04-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawls", "0011_auto_20230410_1518"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="title",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
