# Generated by Django 2.2 on 2023-04-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawls", "0012_auto_20230416_1539"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crawl",
            name="title",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
