# Generated by Django 3.2 on 2023-05-05 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("crawls", "0014_auto_20230505_0937"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="crawl",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="crawls.crawl",
            ),
        ),
    ]
